SEPARATE_ARGUMENTS(SOURCES)
file(MAKE_DIRECTORY ${OUTPUTDIR}/generated/)
set(filename_h "${OUTPUTDIR}/generated/sha256versionfile.h")
set(filename_cpp "${OUTPUTDIR}/generated/sha256versionfile.cpp")

file(WRITE ${filename_h} "#ifndef __SHA256VERSIONFILE_H__\n")
file(WRITE ${filename_cpp} "#include \"sha256versionfile.h\"\n")
foreach(VERSIONED_FILE ${SOURCES})
    file(SHA256 ${VERSIONED_FILE} VERSION)
    set(FANCY_VERSION "= {\n    ")
    foreach(part RANGE 0 62 2)
        string(SUBSTRING ${VERSION} ${part} 2 PART0)
        set(FANCY_VERSION "${FANCY_VERSION} 0x${PART0}")
        if(part LESS 62)
            set(FANCY_VERSION "${FANCY_VERSION},")
            math(EXPR linebreak "(${part}+2) % 16")
            if(linebreak EQUAL 0)
                set(FANCY_VERSION "${FANCY_VERSION}\n    ")
            endif()
        endif()
    endforeach()
    set(FANCY_VERSION "${FANCY_VERSION}\n};")
    set(FILE_VARIABLE "${VERSIONED_FILE}")
    get_filename_component(FILE_VARIABLE "${VERSIONED_FILE}" NAME)
    string(REPLACE "." "_" FILE_VARIABLE "${FILE_VARIABLE}")
    set(FILE_VARIABLE "unsigned char tesla_sha256_${FILE_VARIABLE}[64]")
    set(FANCY_VERSION "${FILE_VARIABLE} ${FANCY_VERSION}")
    file(APPEND ${filename_cpp} "${FANCY_VERSION}\n")
    file(APPEND ${filename_h} "extern ${FILE_VARIABLE};\n")
endforeach()
file(APPEND ${filename_h} "#endif")
